### ISSUE TITLE
Are there any branches for v1?

### ISSUE THREAD

**Issue by Tei1988** [BossaConsulting/phpspec2-expect#33]
I found some matchers listed below are not enabled in v1.0.3.
- ArrayKeyValueMatcher
- StringContainMatcher

I want to use phpspec 2.
So, I can't use v2.0.0.

I want to send PR but I couldn't find any branches for v1.
So I hope the new branch for v1 is created.

**Comment by mlopes** [comment]
There's some tags for versions 1.x, you can find them here:https://github.com/BossaConsulting/phpspec2-expect/releases

I suggest closing this issue.
