### ISSUE TITLE
making it work with phpspec ~3.2

### ISSUE THREAD

**Issue by andho** [BossaConsulting/phpspec2-expect#38]
Currently the compatibility for phpspec2-expect is up to phpspec ~3.1. Waiting for release compatible with phpspec ~3.2.

**Comment by andho** [comment]
I see that master branch supports phpspec >= 3.2.0 < 3.3.0. But I don't see tests for new matchers:

* TriggerMatcher
* IterateMatcher
* ApproximatelyMatcher

Also does it mean < 3.2.0 is no longer supported and if supporting < 3.2.0, how to handle tests for the above 3 new Matchers which are not available for < 3.2.0.

**Comment by andho** [comment]
@MarcelloDuarte ping.

**Comment by mlopes** [comment]
@andho would PR #39 fix this?

**Comment by andho** [comment]
@mlopes yeah that looks good.

**Comment by mlopes** [comment]
Thanks, going to merge it and close this ticket then.
