### ISSUE TITLE
Missing file and line makes it difficult to figure out where the failure is

### ISSUE THREAD

**Issue by walterdolce** [BossaConsulting/phpspec2-expect#46]
Hi. 
In a scenario like the one below, where `$foo` and/or `$baz` return `00000`:
```
# code

expect($foo)->notToBe('');

# more code

expect($baz)->notToBe('');
```

The error one gets (as expected) is:
```
Expected <value>""</value>, but got <value>"00000"</value>. (PhpSpec\Exception\Example\NotEqualException)
```

The fact that `__FILE__` and `__LINE__` is missing makes it painful for engineers to figure out where exactly the failure is. One has to resort to using `var_dump`, etc to get a clue.

This is basic yet fundamental info which should be included in the errors.

**Comment by debo** [comment]
@walterdolce we didn't forget about you. I'll have a look into this as soon as I can.

**Comment by mlopes** [comment]
@walterdolce this repo has been forked to friends-of-phpspec, maybe re-open the issue there, and close it here?

**Comment by walterdolce** [comment]
![](https://images.squarespace-cdn.com/content/v1/5af2cd541aef1d8172eac5c7/1563523238396-F24CVDJR1U6DGZLCEHCA/ke17ZwdGBToddI8pDm48kNKU_v8gJAcxDrmB-soKvj1Zw-zPPgdn4jUwVcJE1ZvWEtT5uBSRWt4vQZAgTJucoTqqXjS3CfNDSuuf31e0tVHCnm8a75afeGmEHZWkl5PmyTMMaUTKBnPyCeVGtabJSWQ6l2WM7tn7mqHTODzkmeM/giphy-10.gif)
