### ISSUE TITLE
Move to BossaConsulting/phpspec-expect

### ISSUE THREAD

**Issue by Sam-Burns** [BossaConsulting/phpspec2-expect#49]
Now that we're moving to PhpSpec version 4, perhaps we should move the repo to remove the `2` from the name.

Github should set up a redirect when we do this.  We may need to manually change Packagist, the installation docs, Travis and any badges on the Readme.

**Comment by Sam-Burns** [comment]
@ubick any thoughts?

**Comment by jaylinski** [comment]
@Sam-Burns Hi! I think this would fit nicely in our https://github.com/friends-of-phpspec org.

If you are interested, please ping @shulard. :)

**Comment by debo** [comment]
Hi @Sam-Burns, hi @jaylinski, a little introduction from me. I've been a little busy lately and I didn't have time to look at the currently open issues, however I was appointed by @MarcelloDuarte and @mlopes as new maintainer of the project. I'm happy with both suggestions, however, about the latter I think there is need for Marcello's and Marco's approval. Thoughts?

**Comment by mlopes** [comment]
As @Sam-Burns said, renaming it in place is very easy and github takes care of the redirects, so things won't break for anyone. For the latter, it would fall to @MarcelloDuarte as he's the one that owns the project.

**Comment by debo** [comment]
I'll wait for @MarcelloDuarte on this one and then action this ticket accordingly. I'll start with the renaming part in the meantime and leave the issue open while we wait for a decision on the latter.

**Comment by jaylinski** [comment]
@debo Can you create a new tag, so `bossa/phpspec-expect` will be on Packagist? (https://packagist.org/packages/bossa/phpspec-expect) Thank you!

**Comment by debo** [comment]
@jaylinski done but I'm not sure it will come up... I think @MarcelloDuarte needs to do something on packagist side for the project to come up.

**Comment by debo** [comment]
Hi @Sam-Burns and @jaylinski I have regretfully let you know that I won't be able to continue supporting this project due to unforeseen personal reasons, and as such I will drop from the group of maintainers. I do hope @mlopes or @MarcelloDuarte can carry on what was started here. All the best.

**Comment by Sam-Burns** [comment]
@debo Thank you for your service :-) Lopes and I will maintain the project as needed.

**Comment by phil-davis** [comment]
Note: there is discussion in #65 about completely forking this to https://github.com/friends-of-phpspec because BossaConsulting seems to have stopped responding.

**Comment by jaylinski** [comment]
ℹ️ I forked the repository and created a new tag:

* https://packagist.org/packages/friends-of-phpspec/phpspec-expect
* https://github.com/friends-of-phpspec/phpspec-expect/releases/tag/4.0.0

**Comment by mlopes** [comment]
ok, I'll close this issue then, since the new repo has the right name, and effectively does all that we discussed in this ticket.
